"""Initial Migration

Revision ID: ccb7f9c25d7f
Revises: 
Create Date: 2025-06-24 13:44:58.728905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb7f9c25d7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    # ### end Alembic commands ###
